// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
import java.util.*;
class Main {
   public static void main(String args[]) throws Exception {
    MyStack t = new MyStack();
    t.load();
    int choice;
    Scanner sca = new Scanner(System.in);
    System.out.println();
    System.out.println(" 1. Test f1 - push (1 mark)");
    System.out.println(" 2. Test f2 - pop (1 mark)");
    System.out.println(" 3. Test f3 - peek (1 mark)");
    System.out.print("    Your selection (1 -> 3): ");
    choice = sca.nextInt();
    sca.nextLine();
    switch(choice) {
       case 1: 
           System.out.println("Before:");
           t.display();
           t.push(1);
           System.out.println("\nAfter:");
           t.display();
           break;
       case 2: 
           System.out.println("Before:");
           t.display();
           t.pop();
           System.out.println("\nAfter:");
           t.display();
           break;
       case 3: 
           System.out.println("Before:");
           t.display();
           t.peek();
           System.out.println("\nAfter:");
           t.display();
           break;
       default: System.out.println("Wrong selection");
      }
     System.out.println();
   }      
 }
