// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
import java.util.*;
class Main {
   public static void main(String args[]) throws Exception {
    MyTree t = new MyTree();
    t.load();
    int r=0;
    int choice;
    Scanner sca = new Scanner(System.in);
    System.out.println();
    System.out.println(" 1. Test f1 - show all nodes in the tree");
    System.out.println(" 2. Test f2 - count nodes");
    System.out.println(" 3. Test f3 - count leaf");
    System.out.println(" 4. Test f4 - count nodes larger than 10 ");
    System.out.print("    Your selection (1 -> n): ");
    choice = sca.nextInt();
    sca.nextLine();
    switch(choice) {
       case 1: 
           System.out.println("Tree:");
           t.inOrder(t.root);
           break;
       case 2: 
           System.out.println("Tree:");
           t.inOrder(t.root);
           r = t.countNode();
           System.out.println("\nNodes in the tree: " + r + "  nodes");
           break;
       case 3: 
           System.out.println("Tree:");
           t.preOrder();
           r = t.countLeaf();
           System.out.println("\nLeaf in the tree: " + r + "  leaf");
           break;
           
        case 4: 
           System.out.println("Tree:");
           t.preOrder();
           r = t.countLargerThan(10);
           System.out.println("\nNodes larger than 10:  " + r + "  nodes");
           break;
       default: System.out.println("Wrong selection");
      }
     System.out.println();
   }      
 }
